version: '3'
services:
  app:
    build:
      context: ./d3-rails-neo4j-docker
      dockerfile: Dockerfile
    platform: linux/amd64
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./d3-rails-neo4j-docker:/u/apps/d3-rails-neo4j-docker
    ports:
      - '3000:3000'
    environment:
      - NEO4J_CONFIG_URL=bolt://host.docker.internal:7687
      - NEO4J_CONFIG_USERNAME=neo4j
      - NEO4J_CONFIG_PASSWORD=admin
    stdin_open: true
    tty: true
  neo4j:
    image: neo4j:4.4.5-community
    platform: linux/amd64
    volumes:
      - $HOME/docker-neo4j/data:/data
    ports:
      - '7475:7474'
      - '7687:7687'
 